function ca = ExperimentCatalog(trace)
% Return the catalog of all experiments.
%
% TRACE -> 1 to show in console info about the experiments in the catalog.
%
% CA <- a cell with as many entries as experiments, each one a struct:
%       .class <- text with the class name
%       .index <- integer for the index within the class
%       .name <- name of the experiment
%       .dens <- an integer for density (NaN if simulated)
%       .dist <- a text for dist
%       .clientsw <- a text for client sw
%       .serversw <- a text for server sw
%       .netw <- a text for the network connection
%       .fdir <- text with the folder (not ended in '/')
%       .fexp <- text with the filename, including extension
%       .fext <- only extension (without '.')
    
    ca = {};

    cl = 'realoct2023';
    ssw = 'linuxphp2023';
    fd = '/DATOS_RSYNC/Investigacion/Papers/web/19 estudio de metodos de modelado de delays para revista con vicente y ana desde proyecto garthim 2023 (pendiente)/paper de modeladores solo/sw/datos experimentos/tomados del roundtripserver';
    fe = 'm';
    de = 1024;
    ca{length(ca)+1} = struct('class',cl,'index',1,...
                               'name','dens1024_local_pcdespacho_oct2023',...
                               'dens',de,'dist','00-local','serversw',ssw,'clientsw','linuxff2023','netw','00-none',...
                               'fdir',fd,...
                               'fexp','dens1024_local_pcdespacho_02y03deoct2023_1715pm_ff_031023.m',...
                               'fext',fe');
    ca{length(ca)+1} = struct('class',cl,'index',2,...
                               'name','dens1024_pinos_pcdespacho_oct2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','linuxff2023','netw','07_2-wififiber',...
                               'fdir',fd,...
                               'fexp','dens1024_pinos_cylonwifiyfibra_05y06deoct2023_1223am_ch_061023.m',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',3,...
                               'name','dens1024_smartphone_pcdespacho_oct2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','androidch2023','netw','09_2-4Gfiber',...
                               'fdir',fd,...
                               'fexp','dens1024_smartphone_4Gyfibra_07y08oct2023_1601pm_ff_071023.m',...
                               'fext',fe);
    de = 65536;
    ca{length(ca)+1} = struct('class',cl,'index',4,...
                               'name','dens65536_local_pcdespacho_oct2023',...
                               'dens',de,'dist','00-local','serversw',ssw,'clientsw','linuxff2023','netw','00-none',...
                               'fdir',fd,...
                               'fexp','dens65536_local_pcdespacho_09y10deoct2023_1658pm_ff_101023.m',...
                               'fext',fe');
    ca{length(ca)+1} = struct('class',cl,'index',5,...
                               'name','dens65536_pinos_pcdespacho_oct2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','linuxff2023','netw','07_2-wififiber',...
                               'fdir',fd,...
                               'fexp','dens65536_pinos_cylonwifiyfibra_20y21deoct2023_1815pm_ff_211023.m',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',6,...
                               'name','dens65536_smartphone_pcdespacho_oct2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','androidch2023','netw','09_2-4Gfiber',...
                               'fdir',fd,...
                               'fexp','dens65536_smartphone_4Gyfibra_11y12oct2023_1806pm_ch_121023.m',...
                               'fext',fe);
    de = 786432;
    ca{length(ca)+1} = struct('class',cl,'index',7,...
                               'name','dens786432_local_pcdespacho_oct2023',...
                               'dens',de,'dist','00-local','serversw',ssw,'clientsw','linuxff2023','netw','00-none',...
                               'fdir',fd,...
                               'fexp','dens786432_local_pcdespacho_16y17deoct2023_1425pm_ff_171023.m',...
                               'fext',fe');
    ca{length(ca)+1} = struct('class',cl,'index',8,...
                               'name','dens786432_pinos_pcdespacho_oct2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','linuxff2023','netw','07_2-wififiber',...
                               'fdir',fd,...
                               'fexp','dens786432_pinos_pcdespacho_21y22deoct2023_1827pm_ff_221023.m',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',9,...
                               'name','dens786432_smartphone_pcdespacho_oct2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','androidch2023','netw','09_2-4Gfiber',...
                               'fdir',fd,...
                               'fexp','dens786432_smartphone_4Gyfibra_19y20oct2023_1946pm_ch_201023.m',...
                               'fext',fe);
    de = 65536;
    ca{length(ca)+1} = struct('class',cl,'index',10,...
                               'name','dens65536_pinos_laptopwifirepetidoryfibra_oct2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','win10ff','netw','06-wifirepeaterfiber',...
                               'fdir',fd,...
                               'fexp','dens65536_pinos_laptopwifrepfib_29y30deoct2023_1204am_ff_301023.m',...
                               'fext',fe);
    de = 1024;
    ca{length(ca)+1} = struct('class',cl,'index',11,...
                               'name','dens1024_pinos_laptopwifirepetidoryfibra_nov2023',...
                               'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','win10ff','netw','06-wifirepeaterfiber',...
                               'fdir',fd,...
                               'fexp','den1024_pinos_laptopwifirepfib_04y05denov2023_847am_ff_051123.m',...
                               'fext',fe);   
    de = 786432;
    ca{length(ca)+1} = struct('class',cl,'index',12,...
                              'name','dens786432_pinos_laptopwifirepfib_nov2023',...
                              'dens',de,'dist','03-pinos','serversw',ssw,'clientsw','win10ff','netw','06-wifirepeaterfiber',...
                              'fdir',fd,...
                              'fexp','dens786432_pinos_laptopwifirepfib_05y06denov2023_1042_ff_061123.m',...
                              'fext',fe);

    cl = 'realpapersensors';
    fd = '/DATOS_RSYNC/Investigacion/Papers/web/19 estudio de metodos de modelado de delays para revista con vicente y ana desde proyecto garthim 2023 (pendiente)/paper de modeladores solo/sw/datos experimentos/paper sensors open ana gago';
    fe = 'txt';
    ca{length(ca)+1} = struct('class',cl,'index',1,...
                               'name','sancho_laser_samebuilding_wifi_2014',...
                               'dens',181*4,'dist','01-samebuilding','serversw','winlaptopsancho','clientsw','linuxff2014','netw','07-wifi',...
                               'fdir',fd,...
                               'fexp','sc1.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',2,...
                               'name','sancho_webcam_20%BW_home_wifi_2014',...
                               'dens',ceil(640*480*1*0.20),'dist','02-samecity','serversw','winlaptopsancho','clientsw','linuxff2014','netw','08-wifi+ISP',...
                               'fdir',fd,...
                               'fexp','sc2.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',3,...
                               'name','sancho_webcam_40%BW_home_wifi_2014',...
                               'dens',ceil(640*480*1*0.40),'dist','02-samecity','serversw','winlaptopsancho','clientsw','linuxff2014','netw','08-wifi+ISP',...
                               'fdir',fd,...
                               'fexp','sc3.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',4,...
                               'name','sancho_webcam_30%NW_home_modemRTC_2014',...
                               'dens',ceil(640*480*1*0.30),'dist','02-samecity','serversw','win32','clientsw','linuxff2014','netw','11-RTC56kbps+ISP',...
                               'fdir',fd,...
                               'fexp','sc4.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',5,...
                               'name','sancho_webcam_100%C_home_modemRTC_2014',...
                               'dens',ceil(640*480*3),'dist','02-samecity','serversw','win32','clientsw','linuxff2014','netw','11-RTC56kbps+ISP',...
                               'fdir',fd,...
                               'fexp','sc5.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',6,...
                               'name','sancho_webcam_10%BW_office_cable_2014',...
                               'dens',ceil(640*480*1*0.10),'dist','01-samebuilding','serversw','win32','clientsw','linuxff2014','netw','03-twisted1Gb',...
                               'fdir',fd,...
                               'fexp','sc6.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',7,...
                               'name','sancho_webcam_50%BW_office_cable_2014',...
                               'dens',ceil(640*480*1*0.50),'dist','01-samebuilding','serversw','win32','clientsw','linuxff2014','netw','03-twisted1Gb',...
                               'fdir',fd,...
                               'fexp','sc7.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',8,...
                               'name','sancho_webcam_100%BW_office_cable_2014',...
                               'dens',ceil(640*480*1),'dist','01-samebuilding','serversw','win32','clientsw','linuxff2014','netw','03-twisted1Gb',...
                               'fdir',fd,...
                               'fexp','sc8.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',9,...
                               'name','surveyor_webcam_5%C_wifi_2014',...
                               'dens',ceil(320*240*3),'dist','01-samebuilding','serversw','surveyorandroid','clientsw','androidGalaxySII','netw','04-wifiadhoc',...
                               'fdir',fd,...
                               'fexp','sc9.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',10,...
                               'name','giraffe_odometry_cable_wifi_2014',...
                               'dens',9323,'dist','01-samebuilding','serversw','miniPCwinCE','clientsw','win32XP','netw','05-wifi+twisted1Gb',...
                               'fdir',fd,...
                               'fexp','sc10.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',11,...
                               'name','phpsimul_echo_argentina_2014',...
                               'dens',20,'dist','05-argentina-malaga','serversw','linuxi7','clientsw','win32XP','netw','10-wifi+twisted1Gb+submarine',...
                               'fdir',fd,...
                               'fexp','sc11.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',12,...
                               'name','babelsimul_odometry_home_2014',...
                               'dens',80,'dist','02-samecity','serversw','linuxi7','clientsw','linuxff2014','netw','09-wifi+twisted1Gb+ISP',...
                               'fdir',fd,...
                               'fexp','sc12.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',13,...
                               'name','arduino_analoginput_local_2014',...
                               'dens',27,'dist','00-local','serversw','arduinoUNOR3','clientsw','linuxff2014','netw','02-USB',...
                               'fdir',fd,...
                               'fexp','sc13.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',14,...
                               'name','phpsimul_echo_cable_2014',...
                               'dens',4,'dist','01-samebuilding','serversw','miniPCwin32','clientsw','linuxff2014','netw','03-twisted1Gb',...
                               'fdir',fd,...
                               'fexp','sc14.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',15,...
                               'name','phpsimul_100%C_local_2014',...
                               'dens',640*480*3,'dist','00-local','serversw','lin32','clientsw','linuxff2014','netw','00-none',...
                               'fdir',fd,...
                               'fexp','sc15.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',16,...
                               'name','phpsimul_laser_cable_2014',...
                               'dens',2048*4,'dist','01-samebuilding','serversw','miniPCwin32','clientsw','linuxff2014','netw','03-twisted1Gb',...
                               'fdir',fd,...
                               'fexp','sc16.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',17,...
                               'name','phpsimul_100%C_cable_2014',...
                               'dens',640*480*3,'dist','01-samebuilding','serversw','linuxff2014','clientsw','linuxff2014','netw','01-cable',...
                               'fdir',fd,...
                               'fexp','sc17.txt',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',18,...
                               'name','phpsimul_100%C_plymouth_2014',...
                               'dens',640*480*3,'dist','04-plymouth(UK)-malaga','serversw','linuxff2014','clientsw','laptoplinuxff2014','netw','10-wifi+twisted1Gb+submarine',...
                               'fdir',fd,...
                               'fexp','sc18.txt',...
                               'fext',fe);
    

    cl = 'sim';
    fd = '<sim>';
    fe = '';
    ca{length(ca)+1} = struct('class',cl,'index',1,...
                               'name','oneregime_LL3_2023',...
                               'dens',-1,'dist','06-undefined','serversw','undefined','clientsw','undefined','netw','12-undefined',...
                               'fdir',fd,...
                               'fexp','1',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',2,...
                               'name','threeregimes_LL3_2023',...
                               'dens',-1,'dist','06-undefined','serversw','undefined','clientsw','undefined','netw','12-undefined',...
                               'fdir',fd,...
                               'fexp','2',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',3,...
                               'name','oneregime_LN3_2023',...
                               'dens',-1,'dist','06-undefined','serversw','undefined','clientsw','undefined','netw','12-undefined',...
                               'fdir',fd,...
                               'fexp','3',...
                               'fext',fe);
    ca{length(ca)+1} = struct('class',cl,'index',4,...
                               'name','oneregime_EXP2_2023',...
                               'dens',-1,'dist','06-undefined','serversw','undefined','clientsw','undefined','netw','12-undefined',...
                               'fdir',fd,...
                               'fexp','4',...
                               'fext',fe);

    if trace
        fprintf('EXPERIMENTS (%d):\n',length(ca));
        for f = 1:length(ca)
            fprintf('\t#%d: [%s:%d] %s, dens %d, net %s, dist %s, serv %s, cli %s\n',f,ca{f}.class,ca{f}.index,ca{f}.name,...
                                                                                       ca{f}.dens,ca{f}.netw,ca{f}.dist,ca{f}.serversw,ca{f}.clientsw);
        end
    end

end
