function emptyperf = PerformanceEmpty()
% Return a performance struct with all fields empty (see PerformanceDef).

    emptyperf = struct('computation',struct('time',[]),...
                       'groundtruth',struct('reqprob',[],...
                                            'experr',[],...
                                            'stderr',[],...
                                            'modeerr',[]),...
                       'prediction',struct('reqerr',struct('sample',[],...
                                                           'model',[]),...
                                           'experr',struct('sample',[],...
                                                           'model',[],...
                                                           'next',[]),...
                                           'stderr',struct('sample',[],...
                                                           'model',[]),...
                                           'modeerr',struct('sample',[],...
                                                            'model',[],...
                                                            'next',[])));
end


